apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  releaseName: cluster-autoscaler-chart
  targetNamespace: kube-system
  chart:
    repository: https://kubernetes.github.io/autoscaler
    name: cluster-autoscaler-chart
    version: 1.1.1
  values:
    podAnnotations:
      "prometheus.io/scrape": "true"
      "prometheus.io/port": "8085"
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    resources:
      requests:
        cpu: "100m"
        memory: "300Mi"
      limits:
        cpu: "1000m"
        memory: "512Mi"
    image:
      repository: "k8s.gcr.io/autoscaling/cluster-autoscaler"
      tag: "v1.17.3"
    priorityClassName: "system-cluster-critical"
    awsRegion: "ap-northeast-1"
    fullnameOverride: "cluster-autoscaler"
    autoDiscovery:
      clusterName: eks-cluster
    replicaCount: 2
    #podDisruptionBudget: |
    #  maxUnavailable: 1
    #  # minAvailable: 2
    extraArgs:
      "node-group-auto-discovery": "asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/eks-cluster"
      "scale-down-utilization-threshold": "0.8"
      "scale-down-unneeded-time": "10m"
      "skip-nodes-with-local-storage": "false"
      "skip-nodes-with-system-pods": "false"
      "expander": "priority"
      "cloud-provider": "aws"
    rbac:
      create: true
      pspEnabled: true
    expanderPriorities: |
        10:
          - .*
        15:
          - .*ondemand-medium.*
        20:
          - .*ondemand-large.*
        25:
          - .*spot-medium.*
        30:
          - .*spot-r5-large.*
        35:
          - .*spot-m5-large.*
        40:
          - .*spot-xlarge.*
        45:
          - .*spot-large.*

