apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  releaseName: cluster-autoscaler-chart
  targetNamespace: kube-system
  chart:
    repository: https://kubernetes.github.io/autoscaler
    name: cluster-autoscaler
    #version: 9.3.2
    version: 9.11.0
  values:
    podAnnotations:
      "prometheus.io/scrape": "true"
      "prometheus.io/port": "8085"
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    priorityClassName: "system-cluster-critical"
    awsRegion: "ap-northeast-1"
    fullnameOverride: "cluster-autoscaler"
    autoDiscovery:
      clusterName: eks-cluster
    replicaCount: 2
    extraArgs:
      "node-group-auto-discovery": "asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/eks-cluster"
      "scale-down-utilization-threshold": "0.8"
      "scale-down-unneeded-time": "10m"
      "skip-nodes-with-local-storage": "false"
      "skip-nodes-with-system-pods": "false"
      "expander": "priority"
      "cloud-provider": "aws"
      "expendable-pods-priority-cutoff": "-10"
    rbac:
      create: true
      pspEnabled: true
    expanderPriorities: |
        50:
          - eks-f2bf12c3-e252-bc75-0408-ab03fdecbfdb
        40:
          - .*spot-large-price.*
        30:
          - .*spot-xlarge-price.*
        20:
          - .*ondemand-large.*
        15:
          - .*ondemand-xlarge.*
        10:
          - .*








